"""Shared validation schemas for API entities."""

from .membership import (
    CREATE_MEMBERSHIP_SCHEMA,
    DELETE_MEMBERSHIP_SCHEMA,
    MEMBERSHIP_ID_QUERY_SCHEMA,
    SEND_CARD_SCHEMA,
    SET_PRICE_SCHEMA,
    UPDATE_MEMBERSHIP_SCHEMA,
)
from .events import (
    CREATE_EVENT_SCHEMA,
    DELETE_EVENT_SCHEMA,
    EVENT_ID_QUERY_SCHEMA,
    UPDATE_EVENT_SCHEMA,
    UPLOAD_EVENT_PHOTO_SCHEMA,
)
from .messages import DELETE_MESSAGE_SCHEMA, REPLY_MESSAGE_SCHEMA
from .newsletter import (
    NEWSLETTER_ID_QUERY_SCHEMA,
    NEWSLETTER_ID_OPTIONAL_QUERY_SCHEMA,
    NEWSLETTER_PARTICIPANTS_SCHEMA,
    NEWSLETTER_SIGNUP_SCHEMA,
    UPDATE_NEWSLETTER_SCHEMA,
)
from .participants import (
    CREATE_PARTICIPANT_SCHEMA,
    DELETE_PARTICIPANT_SCHEMA,
    GET_PARTICIPANT_SCHEMA,
    GET_PARTICIPANTS_BY_EVENT_SCHEMA,
    SEND_LOCATION_SCHEMA,
    SEND_LOCATION_TO_ALL_SCHEMA,
    SEND_TICKET_SCHEMA,
    UPDATE_PARTICIPANT_SCHEMA,
    CHECK_PARTICIPANTS_SCHEMA,
)
from .purchases import (
    CREATE_PURCHASE_SCHEMA,
    DELETE_PURCHASE_SCHEMA,
    PURCHASE_ID_QUERY_SCHEMA,
)
from .settings import GET_SETTING_SCHEMA, SET_SETTING_SCHEMA
from .event_payment import CAPTURE_ORDER_SCHEMA, PREORDER_SCHEMA
from .request import (
    inject_payload_fields,
    inject_payload_dto,
    inject_query_params,
    require_json_body,
    validate_body_fields,
    validate_query_params,
)

__all__ = [
    "UPDATE_MEMBERSHIP_SCHEMA",
    "CREATE_MEMBERSHIP_SCHEMA",
    "DELETE_MEMBERSHIP_SCHEMA",
    "MEMBERSHIP_ID_QUERY_SCHEMA",
    "SEND_CARD_SCHEMA",
    "SET_PRICE_SCHEMA",
    "EVENT_ID_QUERY_SCHEMA",
    "NEWSLETTER_ID_OPTIONAL_QUERY_SCHEMA",
    "NEWSLETTER_ID_QUERY_SCHEMA",
    "NEWSLETTER_PARTICIPANTS_SCHEMA",
    "NEWSLETTER_SIGNUP_SCHEMA",
    "UPDATE_NEWSLETTER_SCHEMA",
    "CREATE_PARTICIPANT_SCHEMA",
    "DELETE_PARTICIPANT_SCHEMA",
    "GET_PARTICIPANT_SCHEMA",
    "GET_PARTICIPANTS_BY_EVENT_SCHEMA",
    "SEND_LOCATION_SCHEMA",
    "SEND_LOCATION_TO_ALL_SCHEMA",
    "SEND_TICKET_SCHEMA",
    "UPDATE_PARTICIPANT_SCHEMA",
    "CHECK_PARTICIPANTS_SCHEMA",
    "GET_SETTING_SCHEMA",
    "SET_SETTING_SCHEMA",
    "CREATE_PURCHASE_SCHEMA",
    "DELETE_PURCHASE_SCHEMA",
    "PURCHASE_ID_QUERY_SCHEMA",

    "DELETE_MESSAGE_SCHEMA",
    "REPLY_MESSAGE_SCHEMA",
    "CREATE_EVENT_SCHEMA",
    "UPDATE_EVENT_SCHEMA",
    "DELETE_EVENT_SCHEMA",
    "UPLOAD_EVENT_PHOTO_SCHEMA",
    "PREORDER_SCHEMA",
    "CAPTURE_ORDER_SCHEMA",
    "require_json_body",
    "validate_body_fields",
    "validate_query_params",
    "inject_payload_fields",
    "inject_payload_dto",
    "inject_query_params",
]
