import localFont from "next/font/local";
import {Navigation} from "@/components/pages/Navigation"
import {AnimatedBackground} from "@/components/pages/AnimatedBackground"
import "./globals.css";
import { Toaster } from 'react-hot-toast'


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-black text-orange-200`}
      >
        <AnimatedBackground />
        <Navigation />
        {children}
        <Toaster position="top-right" reverseOrder={false} /> {/* Posizione opzionale */}

      </body>
    </html>
  );
}
